### ISSUE TITLE
Ace-Jump may stuck Emacs

### ISSUE THREAD

**Issue by razcampagne** [winterTTr/ace-jump-mode#12]
Hi,

In the unlucky event when I am using Ace-jump to move around and it waits for me to input the highlighted character to go where I want and another buffer pops up (like an erc buffer, as it happenned to me just now), Ace-Jump is still waiting for me to input a character. From there, whatever I input, I always get the error  "[AceJump] Internal Error: invalid tree node type" and C-g or any other command works anymore so I have to kill emacs.

I'm not really sure how you can fix a problem like that but I thought I better report it.

Apart from that, it works very well. Thank you !

**Comment by winterTTr** [comment]
Thanks for reporting this problem. I am sorry that I do not use some popup function ever, that's why I never test such scenario.

If I guess correctly, that is because, currently, ace jump mode 1.1 will only work for a specific buffer. And all the internal status is local to that ( buffer local variables ).

So when some other buffer get the focus, the internal status to the new buffer is not consider to be correct.

Now, ace jump 2.0 is under development and will be release recently:
in 2.0, all the status is global sharing, so I guess, this problem will not happen any more for you.

If you want to resolve this problem right now, i have two suggestion:
- One is try the new 2.0, which is currently on branch FB-Global-AJ, and the code is almost completed for release

> git clone https://github.com/winterTTr/ace-jump-mode.git
> git checkout FB-Global-AJ
- Two is comment all the `make-variable-buffer-local` calls in ace jump 1.0 and try again

``` elisp
    ; (make-variable-buffer-local 'ace-jump-mode)
    ; (make-variable-buffer-local 'ace-jump-background-overlay)
    ; (make-variable-buffer-local 'ace-jump-search-tree)
    ; (make-variable-buffer-local 'ace-jump-query-char)
    ; (make-variable-buffer-local 'ace-jump-current-mode)
```

I will try to config some popup environment later, and test. So that may takes some time.

**Comment by razcampagne** [comment]
Thank you for your quick reply.

I will try the other branch, see if the problem occur again.

**Comment by winterTTr** [comment]
Hi,  razcampagne

I test the latest 2.0 RC version, which is already on the master branch now.
When irc popup a window,
My emacs will remain the cursor on the original window, does not focus the cursor to the popup window, is this the same to you? If yes, the new version is working correct, will not stuck emacs right now.

I use the emacs 24 windows version to test, I am not sure if that is the same behavior for your case.
If so, I think we can close this bug. If not, please describe more detail about your case.

**Comment by razcampagne** [comment]
Hi,

The problem occured when the buffer I worked with was just replaced by an erc one so the focus never had to go to another window… This might actually be an erc bug.

But with the global ace-jump approach, I never had the problem again, so I guess you can close the bug. Sorry for not giving a feedback earlier.

**Comment by winterTTr** [comment]
If you cannot meet the problem with new version until now, I suggest to
close this bug currently.
And once you meet the problem again, you can open a new bug, so that I can
continue to investigate.
Thanks for your feedback, enjoy ace jump~~

-winterTTr

**Comment by razcampagne** [comment]
Will do.

Thanks
