### ISSUE TITLE
ace-jump-mode in elpa is outdate according to your README at github

### ISSUE THREAD

**Issue by redguardtoo** [winterTTr/ace-jump-mode#16]
After installing the latest package through elpa, emacs keep bugging me on the file in elpa/ace-jump-mode-blah/some-file.el while be overriding. Looks emacs don't that package is already installed.

Anything wrong when you make the package?

**Comment by winterTTr** [comment]
Sorry for the late response, recent is kinda busy life :-)

I do not use elpa before, but after some test, I guess you are using the marmalade repository for package.el.
Right now, the owner ( which is the one who update the package ) of "ace jump mode" is not me, so that I cannot update the package from my side. I have contact the owner so we can wait for his response.

If you are not using marmalade, please give me some more detail about your configuration for your elpa, so that I can continue some other investigation.

**Comment by redguardtoo** [comment]
Yes, I'm using marmalade. No worries, I can wait ;)

**Comment by winterTTr** [comment]
It is a good news that I finally found the owner on marmalade.
He has deleted the repository on marmalade, and I upload a latest version on it. I think there should be no problem now, you can have a try.

BTW, the former owner also suggest to use MELPA(http://melpa.milkbox.net/) instead of marmalade.
You may also have a try about that. Enjoy emacs :-)

**Comment by redguardtoo** [comment]
Perfect, thank you.
