### ISSUE TITLE
minor issue : ace-jump-mode.el 's encoding tag

### ISSUE THREAD

**Issue by joonhwan** [winterTTr/ace-jump-mode#22]
In Windows, utf-8-unix encoding with git clone's side effect doesn't work in harmony.
emacs open your file utf-8-unix but git change its line fead already into /r/n 

Apparently this might be not that much problem, but while using el-get and installing ace-jump-mode, it spits out 
compilation error "end of file blah blah".

Thanks for this great handy mode

**Comment by winterTTr** [comment]
I think, the original source file for ace jump mode is utf-8-unix, So if you check out this file as it is, the file format should be correct.

If you using git under windows, please check the config 

> git config --get core.autocrlf
> If it is true, the git will convert the line ending automatically to dos format, that will lead to a problem.

**Comment by joonhwan** [comment]
Oh, I see. Mine is 'true' over that config.

Though It may not sound relevant to ace-jump-mode, I think the source code coding tag should be "utf-8-auto" in this case(which is more general and neutral between platforms). el-get package management can't just download ace-jump-mode and byte-compile it smoothly without handling it manualy.
If I set mentioned git config parameter globally, other projects may be affected(wronly).

I'm learning more and more about emacs nowadays(though using it quite for a while) and this can be good case study for me and waiting for your advice or opinion.

**Comment by winterTTr** [comment]
As ace jump mode is on a git repository, so when you use el-get to "download" the ace jump mode source code, the el-get will actually use git.exe to download the source file , that's why the "autocrlf" will affect the line ending of ace jump source file, because the git will convert the line ending to CR/LF under windows OS.  

It seems several guys has reported the same problem as you, i will consider to change the file encoding variable.
Thanks for your suggestion.

**Comment by joonhwan** [comment]
Thanks. I think this issue can be closed enough ;-)
