### ISSUE TITLE
query chars: only ascii?

### ISSUE THREAD

**Issue by ghost** [winterTTr/ace-jump-mode#3]
line 187 

> we can only allow to query printable ascii char

Why this restriction?

Why shouldn't you be able to jump to
1. braces, quotes, etc. (which are printable)
2. any characater that appears in your file, e.g. ä, é, etc.

I can see why you only allow `[A-Za-z]` as _jump_ characters since they should be easy to enter on a QUERTY keyboard but query characters should be pretty much all possible characters.

**Comment by winterTTr** [comment]
Firstly, I must say sorry for that, i do not update this document even though I have changed some code.
1. braces, quotes, etc. (which are printable)
   Currently, these characters can be used as the query char. Of course, you should use char mode( C-u C-SPC ) to query them instead of word-mode.
2. any characater that appears in your file, e.g. ä, é, etc.
   The most important requirement for ace jump is not “ascii", but "printable". 
   Cause currently, I use overlay to display the possible jump position. If the query character is not printable, it may lead to infinite loop or weird display, neither of which is good for the user.
   So, I have to add some limitation on that, which currently is all the possible printable character of ascii.
   But i am sorry that, I do not find a good way to identify if any character is printable or not. That's why this limitation exists.
   If you have any good idea, i am really looking forward that you can share with me and of course I can improve the ace jump  for all the user.

**Comment by ghost** [comment]
1. Sorry, I saw that this was actually possible.
2. My knowledge of overlays is limited so I am afraid I can't help you. I use ace-jump mainly for source code navigation which doesn't have a lot of non ASCII characters.

But thanks for the package anyway, it's a fun and useful tool.

**Comment by winterTTr** [comment]
I am really happy that you like ace jump and it can help you.
I may try to improve this limitation after some investigation, and also really look forward to your good idea at anytime.  :D

**Comment by boykov** [comment]
Idea for characters а, ä, é, etc. "Regexp layer" works for any character. "Ace-jump layer" doesn't know about substitution. "Glue layer" realizes map between ascii and non-ascii. See my example https://github.com/boykov/ace-jump-mode/commit/2d56d7848a82b495377bcc7a0bb191dea36d2196
