### ISSUE TITLE
is it possible to jump to tabbar and select it

### ISSUE THREAD

**Issue by wangyuehong** [winterTTr/ace-jump-mode#43]
it seems no way now...

**Comment by winterTTr** [comment]
Right now, the tabbar is using so-called "header line" of emacs to implement.
Emacs is using "header-line-format" to format the content firstly and show it in "header line" area. I only know the format string instead of the final formatted string. So I _cannot_ control the final formatted string via overlay right now.

So the conclusion is I have no idea how to jump to "header line" at this moment.
